#include <stdio.h>
#include <string.h>
#include <stddef.h>
#include <stdlib.h>
#include <ctype.h>

/* This file was generated by QuasiBASIC to C translator */
/* qb2c  ver.3.41 Free Version 04 May 2000
Check out the Pay version at http://random.com.hr/products/                            */

#define LMAX 1025 /* Max strig length */

/* Function declarations */
extern char  *INPUT(const char*, int);

/* Shared variables and arrays declarations */
static char tws__S[LMAX];

/* Open files pointers */

main()
{
 static float na, ka, kha, ga;

 while(sscanf(INPUT("ऊँचाई: ",0),"%f",&na) != 1 && tws__S[0] != '\n')
 { printf("Redo from start:\n"); }
 printf("% .7G \n",na);
 for(ka = 1; ka <= na; ka++)
 {
  for(kha = 1; kha <= (na - ka); kha++)
  {
   printf("%s"," ");
  }
  for(ga = 1; ga <= ka; ga++)
  {
   printf("%s","&");
  }
  printf("%s\n","");
 }
 for(ka = (na - 1); ka >= 1; ka = ka-1)
 {
  for(kha = 1; kha <= (na - ka); kha++)
  {
   printf("%s"," ");
  }
  for(ga = 1; ga <= ka; ga++)
  {
   printf("%s","&");
  }
  printf("%s\n","");
 }
 exit(0);
} /* End of MAIN */

/* Translates of used QB's intrinsic functions: */

extern char *INPUT(const char *a_S, int i)
{
 if(i == 0) printf("%s",a_S);
 if(i == 1) printf("%s? ",a_S);
 fgets(tws__S,255,stdin);
 tws__S[strlen(tws__S)-1]='\0';
 return tws__S;
}
